- name: Deploy HTML via SSH
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_KEY }}
    source: "app/*"
    target: "/var/www/html"
    script: |
      sudo chown -R www-data:www-data /var/www/html
      sudo systemctl restart apache2
